version: '3.7'

services:
  minio:
    image: minio/minio
    command: server /data
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=abcdefg
      - MINIO_ROOT_PASSWORD=secretsecretsecret
    volumes:
      - ./minio:/data
