# Generated by Django 4.1.7 on 2023-05-20 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_alter_challengegroup_owner_alter_challengeuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
