# Generated by Django 4.1.7 on 2023-05-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_groupsubmit_created_at_groupsubmit_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='tag',
            field=models.CharField(default='vision', max_length=20),
        ),
    ]
