# Generated by Django 4.1.7 on 2023-06-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_remove_groupsubmit_user_alter_groupsubmit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubmit',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
