# Generated by Django 4.1.7 on 2023-06-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_mlsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengephase',
            name='tag',
        ),
    ]
