# Generated by Django 4.1.7 on 2023-06-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_remove_challengephase_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupParticipation',
        ),
    ]
