# Generated by Django 4.1.7 on 2023-06-25 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_delete_groupparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengephase',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 23, 51, 45, 999541, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengephase',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 23, 51, 54, 89360, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
